-- CreateEnum
CREATE TYPE "OnboardEnum" AS ENUM ('NEW', 'INITIATED', 'PHONE_VERIFIED', 'SET_PASSCODE', 'SET_PIN', 'KYB_STARTED', 'KYB_SUBMITTED', 'KYB_APPROVED', 'KYB_FAILED', 'COMPLETED');

-- AlterTable
ALTER TABLE "users" ADD COLUMN     "onboarding" "OnboardEnum" NOT NULL DEFAULT 'NEW';
